services:
  backend:
    image: node:22
    working_dir: /app
    command: yarn start
    expose:
      - "3000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production

  caddy:
    image: caddy:2
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./frontend/dist:/srv
      - ./caddy:/etc/caddy
    depends_on:
      - backend
  
volumes:
  caddy_data:
  caddy_config:
